# Generated by Django 4.2.3 on 2024-04-17 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_data_de_entrega_entrega_data_de_entrega_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frutas',
            old_name='preco_unitario',
            new_name='preco_individual',
        ),
        migrations.RenameField(
            model_name='verduras',
            old_name='preco_unitario',
            new_name='preco_individual',
        ),
    ]
