# Generated by Django 4.2.3 on 2024-04-17 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_data_de_entrega_entrega_data_da_entrega_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='preco_individual',
            new_name='preco_individual_Item',
        ),
    ]
