# Generated by Django 4.2.3 on 2024-04-18 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_preco_individual_item_preco_individual_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frutas',
            options={'verbose_name_plural': 'Frutas'},
        ),
    ]
