# Generated by Django 4.2.3 on 2024-04-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_frutas_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='preco_individual_Item',
        ),
        migrations.AddField(
            model_name='item',
            name='preco_individual_item',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=10),
        ),
    ]
